addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"             % "1.5.7")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"        % "1.5.12")
addSbtPlugin("com.github.sbt"            % "sbt-release"           % "1.1.0")
addSbtPlugin("com.lightbend.sbt"         % "sbt-java-formatter"    % "0.8.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"            % "5.10.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"          % "0.4.3")
addSbtPlugin("net.aichler"               % "sbt-jupiter-interface" % "0.11.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"          % "2.5.0")
