addSbtPlugin("com.github.sbt"       % "sbt-ci-release"        % "1.11.2")
addSbtPlugin("com.github.sbt"       % "sbt-release"           % "1.4.0")
addSbtPlugin("com.github.sbt"       % "sbt-java-formatter"    % "0.10.0")
addSbtPlugin("com.github.sbt"       % "sbt-header"            % "5.11.0")
addSbtPlugin("com.github.sbt.junit" % "sbt-jupiter-interface" % "0.17.0")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"          % "2.5.6")
addSbtPlugin("com.github.sbt"       % "sbt-jacoco"            % "3.5.0")
addSbtPlugin("org.typelevel"        % "sbt-tpolecat"          % "0.5.2")
