name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [2.12.16, 2.13.8, 3.1.3]
        java: [8, 11, 17]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: sbt
    - name: Build with sbt
      run: sbt ++${{ matrix.scala }} build
