name: Build and Test

on:
  pull_request:
    branches:
      - main
      - series/**
  push:
    branches:
      - main
      - series/**
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [2.13.x, 3.3.x]

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: ⚙️ Run build
        run: sbt ++${{ matrix.scala }} build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: "**/target/test-reports/*.xml"
          require_tests: true
          check_name: "${{ matrix.java }}-${{ matrix.scala }}-${{ matrix.project }}"
      - name: Create Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/target/test-reports/*.xml"
        if: always()
      - name: Code Coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
