name: Build and Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [2.13.x, 3.3.x]
        java: [8, 11, 17]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: sbt
    - name: Build with sbt
      run: sbt ++${{ matrix.scala }} build
    - name: Create test summary
      uses: test-summary/action@v2
      with:
        paths: '**/target/test-reports/*.xml'
      if: always()
