name: Release
on:
  push:
    tags: ["**"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.repository == 'SimY4/coregex'
      && !contains(toJSON(github.event.commits.*.message), '[skip release]')

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Release with sbt
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
